on: [push, pull_request]

jobs:
  runself:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Run local action
        uses: ./
      - run: which bazelisk
      - run: which bazel
      - run: bazelisk
      - run: bazelisk --version
      - run: bazel --version
      - run: echo 3.2.0 > .bazelversion
      - run: bazelisk
      - run: bazelisk --version
      - run: bazel --version
